---
title: "Stata Trainings and Tutorials"
author: "Data Team, [Center on Budget and Policy Priorities](https://www.cbpp.org)"
output: 
  html_document:
    theme: paper
---

These materials are published under the license available [here](https://github.com/CenterOnBudget/stata-trainings/blob/master/LICENSE).


### Supplementary Materials for the Stata Course Track

#### [Exporting Stata Tables to Excel](https://centeronbudget.github.io/stata-trainings/stata-tables-to-excel/export_stata_tables_to_excel.html)

Prerequisites: 

- Previous modules in the [Stata Course Track](https://airtable.com/shrnwSpHYzXRlbY20)

#### [Survey Data Analysis with Stata, Part 1: Survey Estimation](https://centeronbudget.github.io/stata-trainings/survey-data-analysis/part_1_survey_estimation.html)
 
Prerequisites: 

- Previous modules in the [Stata Course Track](https://airtable.com/shrnwSpHYzXRlbY20)
- Skim [Stata User's Guide, Chapter 11, Section 4.3, Factor variables](https://www.stata.com/manuals/u11.pdf#page=20)

#### [Survey Data Analysis with Stata, Part 2: Exporting Estimation Results](https://centeronbudget.github.io/stata-trainings/survey-data-analysis/part_2_exporting_estimation_results.html)

Prerequisites: 

- Previous modules in the [Stata Course Track](https://airtable.com/shrnwSpHYzXRlbY20)
- Survey Data Analysis with Stata, Part 1: Survey Estimation
- Skim [Stata User's Guide, Chapter 14, Matrix expressions](https://www.stata.com/manuals/u14.pdf) (skip section 14.6)

### American Community Survey Microdata Tutorials

#### [Creating a Merged Person-Household ACS PUMS Dataset](https://centeronbudget.github.io/stata-trainings/acs-pums/merged_person_hhld_dataset.html)

Prerequisites:

- The [Stata Course Track](https://airtable.com/shrnwSpHYzXRlbY20)
- The [ACS PUMS Course Track](https://airtable.com/shro7EJEu66uXuqp3)

#### [Creating a Custom Multi-year ACS PUMS Dataset](https://centeronbudget.github.io/stata-trainings/acs-pums/custom_multiyear_dataset.html)

Prerequisites:

- The [Stata Course Track](https://airtable.com/shrnwSpHYzXRlbY20)
- The [ACS PUMS Course Track](https://airtable.com/shro7EJEu66uXuqp3)

